version: 2

updates:
  # Monthly check for PHP dependency updates.
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    prefix-commits: true
    commit-message:
      prefix: "PHP package updates"
    labels:
      - "php"
      - "dependencies"

  # Weekly check for PHP security updates.
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    prefix-commits: true
    commit-message:
      prefix: "PHP security updates"
    labels:
      - "php"
      - "security"
    # Only process security updates, ignore version updates.
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  # Monthly check for NCIDS theme NPM updates
  - package-ecosystem: "npm"
    directory: "/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end"
    schedule:
      interval: "monthly"
    prefix-commits: true
    commit-message:
      prefix: "ncids theme"
    group-by: "update-type"
    labels:
      - "npm"
      - "dependencies"

  # Weekly check for NCIDS theme NPM security updates
  - package-ecosystem: "npm"
    directory: "/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end"
    schedule:
      interval: "weekly"
    prefix-commits: true
    commit-message:
      prefix: "ncids theme"
    group-by: "update-type"
    labels:
      - "npm"
      - "security"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
