version: 2

updates:

  # Weekly check for PHP dependency updates.
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      # The morning after Drupal security releases.
      interval: "weekly"
      day: "thursday"
      time: "05:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "PHP package updates"
    groups:
      composer-dependencies:
        dependency-type: "production"
        applies-to: "version-updates"
      composer-security:
        dependency-type: "production"
        applies-to: "security-updates"
    # Don't try to update Drupal core.
    ignore:
      - dependency-name: "drupal/core-*"


  # Monthly check for NCIDS theme NPM updates
  - package-ecosystem: "npm"
    directory: "/docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ncids theme"
    groups:
      ncids-dependencies:
        dependency-type: "production"
        applies-to: "version-updates"
      ncids-security:
        dependency-type: "production"
        applies-to: "security-updates"

